
const 神话再临taici = {
    //神赵云
	"#TAFjuejing1": "龙缚于渊，虽万仞在身，志犹存于八荒！",
	"#TAFjuejing2": "将临死地，必效刑天，舞干戈以征四海！",
    "#TAFlonghun1": "八尺之身，秉义承武，胸腹可栖万丈苍龙！",
    "#TAFlonghun2": "左执青釭，右擎龙胆，此天下，可有挡我者！",
    "#TAF_zhaoyun:die": "亢龙有悔，恨未除天狼于人间。",
    //神庞统
	"#TAFxuanyu1": "红鸾锁曈日，三千练实腾空起，此物最相思!",
	"#TAFxuanyu2": "玉壶妆梧桐，醴泉映东风，火凤归来耀长安!",
    "#TAFfenshen1": "灯火映阑珊，谁家麒麟入梦，吹落繁星如雨?",
    "#TAFfenshen2": "长空琼宇飞玉屑，千树黄金缕，万里起福灯。",
    "#TAFyuhuo1": "歌一曲，酒一觞，邀君醉琼浆，东风盈暖房。",
    "#TAFyuhuo2": "醒又醉，醉复眠，迟日江山如画，何人不流连?",
    "#TAF_pangtong:die": "孔明，好酒，好酒!",
    //姜太虚
	"#TAFjingtu1": "怡然独向九霄中坐看浮生做梦。",
	"#TAFjingtu2": "阴阳化生清浊自分。",
    "#TAFjuechen1": "醒时恐为梦一场，身世俱望，何处是吾乡？",
    "#TAFjuechen2": "为了这片土地，我需要力量。",
    "#TAFshenqu1": "时间冲淡了，我的记忆，也冲散了他们的轮廓。",
    "#TAFshenqu2": "庭前旧梅泛新香，当时故人如今不在旁。",
    "#TAF_jiangtaixu:die": "不能在这里停下。",
    //瞳羽
	"#TAFtianci1": "虚妄之伤？天赐的屏障在守护我呢。",
	"#TAFtianci2": "雷与火交替，像星星眨眼睛呢。",
    "#TAFxingqi1": "呀，这就是上天赐的小小考验吗？",
    "#TAFxingqi2": "嗯，天赐的火焰，也要好好接住呢。",
    "#TAFxingpan1": "星星说可以拿，那就收下啦。",
    "#TAFxingpan2": "哎呀，星星骗人，不过牌还给你哦。",
    "#TAFxingpan3": "星盘，要再陪人家玩一会吗？",
    "#TAFxingpan4": "夜幕降临，要换个颜色啦。",
    "#TAF_tongyu:die": "无。",
    //瞳羽
	"#TAFshuangjiang1": "霜降有时，星归有期，此身再无倦意。",
	"#TAFshuangjiang2": "锦囊藏玄机，可瞒不过天赐的雷火哦。",
    "#TAFxuewu1": "雪舞的规则，偶尔也可以任性哦。",
    "#TAFxuewu2": "黑丝褪作雪，星轨转无声。",
    "#TAFxuewu3": "雪地无边，我的心意，能抵达遥远的彼端吗？",
    "#TAFxuewu4": "霜雪虽冷，却亦想给世间添一丝温情。",
    "#TAFxingpan_shadow1": "这是，只属于我们的回合哦！",
    "#TAFxingpan_shadow2": "星光落进手心时，手心的牌，也变成星辰了吗？",
    "#TAFxingpan_shadow3": "这张牌，是天地借它来吻我吗？",
    "#TAFxingpan_shadow4": "星星不愿离开，那就留在我身边吧。",
    "#TAF_tongyu_shadow:die": "无。",
};
const 隐忍天弓taici = {
    //司马懿
	"#sunquanmou1": "洛水为誓，皇天为证，吾意不在刀兵。",
    "#sunquanmou2": "以谋代战，攻形不以力，攻心不以勇。",
    "#sunquanmou3": "鸿门之宴虽歇，会稽之胆尚悬，孤岂姬、项之辈。",
    "#sunquanmou4": "昔藏青锋于沧海，今潮落，可现兵！",
    "#sunxiongyi1": "烽烟起大荒，戎军远役，问不臣者谁？",
    "#sunxiongyi2": "挥斥千军之贲，长驱万里之远。",
    "#sunxiongyi3": "率土之滨皆为王臣，辽土亦居普天之下。",
    "#sunxiongyi4": "青云远上，寒锋试刃，北雁当寄红翎。",
    "#sunpingling1": "煞星聚顶，你死到临头了！",
    "#sunpingling2": "天狼星光大盛，天下易主可期。",
    "#sunpingling3": "天命，也由我来定!",
    "#sunpingling4": "司马氏乃天命之所加矣。",
    "#sun_simayi:die": "以权谋而立者，必失大义于千秋。",
    //张春华
	"#sunjueqing1": "多情不若绝情好。",
    "#sunjueqing2": "凭君莫话封侯事，一将功成万骨枯。",
    "#sunjueqing3": "繁星映月满欢喜，悲欢离合总无情。",
    "#sunjueqing4": "劝君多珍重，此间不相见。",
    "#sunshangshi1": "酒不醉人人自醉，情不伤人人自负。",
    "#sunshangshi2": "女人，也该对自己狠一点。",
    "#sunshangshi3": "何处蓝染玫色起，伤尽三千痴缠意。",
    "#sunshangshi4": "青一缕冷香远，逝花落，笑靥消。",
    "#sun_zhangchunhua:die": "夫妻情分已尽，累了。",
};
const 鼎足三分taici = {
    //曹操
	"#thunderguixin1": "大忠似奸，留一世功名，前人赞，今人叹，后人美！",
    "#thunderguixin2": "乱世称雄，立一方基业，屯万兵，聚百将，拥千城!",
    "#thunderchiling1": "挟天子以令不臣。",
    "#thunderchiling2": "历史永远由胜利者书写! ",
    "#thunderfeiying1": "将才皆在，保我无忧。",
    "#thunderfeiying2": "我有嘉宾，鼓瑟吹笙。 ",
    "#thunderhujia1": "兵戈斧钱何须虑，我有虎卫三千人！",
    "#thunderhujia2": "一将临阵涉险地，三军齐卫夸虎贵!",
    "#thunder_caocao:die": "假使奉孝在此，不使孤至此……",
    
    //刘备
	"#firezhaoren1": "我将丹心酿烈酒，且取一觞慰风尘。",
    "#firezhaoren2": "余酒尽倾江海中，与君共宴天下人。",
    "#firezhaolie1": "仁言利博，以微惠众。",
    "#firezhaolie2": "上德若谷，下布万民。 ",
    "#firedilu1": "此战，有将军在，方可胜。",
    "#firedilu2": "蜀汉霸业，方需将军出战。 ",
    "#firejieying1": "虎将护身，天险可破。",
    "#firejieying2": "蜀将一心，社稷千秋。",
    "#firejieying_jieyi1": "卿乃志同之股肱，国贼当前，可欲诛之。",
    "#firejieying_jieyi2": "请君振炎汉之武运，除篡国之逆贼。",
    "#fire_liubei:die": "离心离德，蜀汉恐危。",
    //孙权
	"#wateryuheng1": "群雄环伺而地势匡佑，先统江海而后率三军。",
    "#wateryuheng2": "人心相异而天道有常，经纬之道在御而非攻。",
    "#wateryuxin1": "泰然处之，方能大事可成。",
    "#wateryuxin2": "多思多谋，筹谋长远。",
    "#wateryulong1": "多谢爱卿了。",
    "#wateryulong2": "贤臣良将在，我心安矣。",
    "#waterquanshu1": "父兄三代营江东，人心相向乾坤定。",
    "#waterquanshu2": "每思赤壁、西陵、逍遥之役，皆感诸君而涕零。",
    "#waterquanshu_quandao1": "得爱卿相救，孤甚感激。",
    "#waterquanshu_quandao2": "东吴俊杰良将在此，岂会败下阵来？",
    "#water_sunquan:die": "望孙氏子孙，能护东吴万年基业。",
};
const 星河皓月taici = {
    //郭嘉
	"#thunderqizuo1": "绸缪于未雨，手握胜机，雨落何妨高歌?",
    "#thunderqizuo2": "此帆济沧海，彼岸日边，任他风雨飘摇！",
    "#thunderqizuo3": "嘉不受此劫，安能以凡人之躯窥得天机!",
    "#thunderqizuo4": "九州为觞，风雨为酿，谁与我共饮此杯?",
    "#thunderlunshi1": "曹公济天下大难，必定霸王之业。",
    "#thunderlunshi2": "智者审于良主，袁公未知用人之机。",
    "#thunderlunshi3": "公有此十胜，败绍非难事尔。",
    "#thunderlunshi4": "嘉窃料之，绍有十败，公有十胜。",
    "#thunderjiding1": "执鞭扫南之日，嘉再贺明公于九泉……",
    "#thunderjiding2": "天命已成，嘉无负明公之恩！",
    "#thunderyiji1": "潺潺流水声，堪堪难遇卿。",
    "#thunderyiji2": "非吾背诺，天不假年。",
    "#thunderyiji3": "兰气幽山酌，酒香随水流。",
    "#thunderyiji4": "清风山水静，为君起雅韵。",
    "#thunder_guojia:die": "生如夏花，死亦何憾?",
    //诸葛亮
	"#starsliangyi1": "情寄三顾之恩，亮必继之以死。",
    "#starsliangyi2": "身负六尺之孤，臣当鞠躬尽瘁。",
    "#starsliangyi3": "此身抱薪，可付丹鼎，五十四年春秋昭炎汉长明。",
    "#starsliangyi4": "南征北伐，誓还旧都，二十四代王业不偏安一隅。",
    "#starssixiang1": "兵者，行霸道之势，彰王道之实。",
    "#starssixiang2": "将为军魂，可因势而袭，其有战无类。",
    "#starssixiang3": "平二川，定三足，恍惚草堂梦里，挥斥千古风流。",
    "#starssixiang4": "战群儒，守空城，今摆乱石八阵，笑谈将军死生。",
    "#starsbazhen1": "轻舟载浊酒，此去，我欲借箭十万。",
    "#starsbazhen2": "主公有多大胆略，亮便有多少谋略。",
    "#starsbazhen3": "三顾之谊铭心，隆中之言在耳，请托臣讨贼兴复之效。",
    "#starsbazhen4": "著大义于四海，揽天下之弼士，诚如是，则汉室可兴。",
    "#stars_zhugeliang:die": "天下事，了犹未了，终以不了了之。",
    //周瑜
	"#moonyingzi1": "火莲绽江矶，炎映三千弱水。",
    "#moonyingzi2": "奇志吞樯橹，潮平百万寇贼。",
    "#moonyingzi3": "江东多锦绣，离火起曹贼毕，九州同忾。",
    "#moonyingzi4": "星火乘风，风助火势，其必成燎原之姿。",
    "#moonyingmou1": "行计以险，纵略以奇，敌虽百万亦戏之如犬豕。",
    "#moonyingmou2": "若生铸剑为犁之心，须有纵钺止戈之力。",
    "#moonyingmou3": "既遇知己之明主，当福祸共之，荣辱共之。",
    "#moonyingmou4": "将者，贵在知敌虚实，而后避实而击虚。",
    "#moon_zhouyu:die": "人生之艰难，犹如不息之长河。",
    //司马徽
	"#iceshuijing1": "好话不言多。",
    "#iceshuijing2": "美言称好，与君共乐。",
    "#icejianjie1": "荐君良臣，定有所获。",
    "#icejianjie2": "你可是人中龙风。",
    "#iceyinshi1": "身在幽静处，大隐山林间。",
    "#iceyinshi2": "长乐山水中，名留久长远。",
    "#ice_simahui:die": "汝等，可不要让我失望啊。",
};
const 惊世银竹taici = {
    //曹纯
	"#thundershanjia1": "虎豹骑，皆天下骁锐!",
    "#thundershanjia2": "缮取治军之道，安抚众军之心。",
    "#thundershanjia3": "兵法之道，有武且要晓人心。",
    "#thundershanjia4": "纲纪督御，不失其理。",
    "#thundershanjia_gongfa1": "百锤锻甲，披之可陷靡阵、断神兵、破坚城！",
    "#thundershanjia_gongfa2": "千炼成兵，邀天下群雄引颈，且试我剑利否！",
    "#thundershanjia_yushou1": "激水漂石，鸷鸟毁折，势如曠弩，勇而不乱。",
    "#thundershanjia_yushou2": "破军罢马，丢盔失甲，疲兵残阵，何以御我？",
    "#thunder_caochun:die": "不胜即亡，唯一死而已!",
    //曹丕
	"#thunderfangzhu1": "爱卿既知朕意，可速赴新任。",
    "#thunderfangzhu2": "卿之过虽可免死，贬斥不能得缓。",
    "#thunderxingshang1": "将军为国捐躯，应该贵礼厚葬。",
    "#thunderxingshang2": "斯人已逝，朕自然记挂于心。",
    "#thundersongwei1": "汉禅归魏，天下皆服。",
    "#thundersongwei2": "魏祚定基，海内匡正。",
    "#thunder_caopi:die": "仲达，勿要负朕佐魏之托……",
    //王基
	"#thunderqizhi1": "斗奇而争，以妙取胜。",
    "#thunderqizhi2": "用计奇略，制敌服心。",
    "#thunderjinqu1": "拒天诛者意沮，而向王化者益固。",
    "#thunderjinqu2": "正则众邪不生，心静则众事不躁。",
    "#thunder_wangji:die": "若子孙不竞，社稷之忧也。",
    //文鸯
	"#thunderquedi1": "尽屠其精锐，可致元气大伤!",
    "#thunderquedi2": "我部折损近半，一举拿下，斩草除根!",
    "#thunderlvli1": "彼消我长，细水长流！",
    "#thunderlvli2": "出入万众，所向皆服。",
    "#thunderchoujue1": "国仇恩怨，就在此战!",
    "#thunderchoujue2": "汝之野心，世人皆知。",
    "#thunder_wenyang:die": "漫漫独行路，凄凉话当年。",
    //钟会
	"#thunderyulei1": "风水轮流转，轮到我钟谋问鼎重几何了。",
    "#thunderyulei2": "汉鹿已失，魏牛犹在，吾欲执其耳。",
    "#thunderyulei3": "空将宝地赠他人，某怎会心甘情愿？",
    "#thunderyulei4": "入宝山而空手回，其与匹夫何异？",
    "#thunderyulei5": "天降大任于斯，不受必遭其殃！",
    "#thunderyulei6": "我欲行夏禹旧事，为天下任！",
    "#thunderfulong1": "今提三尺剑，开万里疆，九鼎不足为重！",
    "#thunderfulong2": "经略四州之地，可钓金鲤于渭水。",
    "#thunderfulong3": "窃钩者诛，窃国者侯，会欲窃九州为狩。",
    "#thunderfulong4": "今长缨在手，欲问鼎九州！",
    "#thunderfulong5": "我若束手无策，诸位又有何施为？",
    "#thunderfulong6": "我有佐国之术，可缚苍龙！",
    "#thunderyujun1": "会不轻易信人，唯不疑伯约。",
    "#thunderyujun2": "与君相逢恨晚，数语难道天下谊。",
    "#thunderyujun3": "于天下觉春秋尚早，于伯约恨相见太迟。",
    "#thunderyujun4": "与君并肩高处，可观众山之小。",
    "#thunderyujun5": "你我虽异父异母，亦可约为兄弟。",
    "#thunderyujun6": "我以国士待伯约，伯约定不负我。",
    "#thunder_zhonghui:die": "伯约误我……",
};
const 期期离火taici = {
    //鲍三娘
	"#firezhenwu1": "红袖爱武妆，不让须眉七尺将，素手可拭刀锋凉。",
    "#firezhenwu2": "青丝绕青锋，此间巾帼战意浓，烈血尽染女儿红！",
    "#firezhenwu3": "凤舞天下，炎翎绽红莲，剑斩九州负义人！",
    "#firezhenwu4": "龙翔八荒，皓鳞濯丹青，刀撰万古春秋义。",
    "#firezhennan1": "南疆有我镇之，定叫蛮夷俯首，再无寇关之意！",
    "#firezhennan2": "提刀镇关而守疆者，非男儿之属，巾帼亦可为！",
    "#firezhennan3": "青锋荡毒瘴，大江破山流！",
    "#firezhennan4": "秋风起，折断岭南十万兵！",
    "#firefangzong1": "情衷此生，愿与君共战于沙场，焉存独活之想！",
    "#firefangzong2": "与君为好之心，纵石烂海枯，山河倒悬亦不改。",
    "#firefangzong3": "红袖青锋，并肩协战，且看龙飞凤翔。",
    "#firefangzong4": "我以此身许忠义，炙炎焚钺锻情丝。",
    "#fire_baosanniang:die": "忘川桥头待君往，三生石上镌三生。",
    //关银屏
	"#firexuehen1": "久恨难消，此仇必报。",
    "#firexuehen2": "就用汝命，为父亲报仇！",
    "#firehuxiao1": "虎啸之威，凤鸣啸引。",
    "#firehuxiao2": "战场虎女的名号，可不是白叫的。",
    "#firefengming1": "血债累累，你，算得清吗！",
    "#firefengming2": "还没有结束呢！",
    "#fire_guanyinping:die": "这仗已败，是我武艺不精。",
    //张星彩
	"#fireshenxian1": "克娴内则，花柔外刚。",
    "#fireshenxian2": "能为夫君分忧，臣妾之责。",
    "#fireqiangwu1": "日暮云沙起，花枪英秀扬。",
    "#fireqiangwu2": "柔彩星动，舞耀蜀汉。",
    "#fireyuzhui1": "凭父忠勇，斩尽贼寇!",
    "#fireyuzhui2": "舍我之力，剿魏国刀枪入库，马放南山，永不进犯我大汉!",
    "#fire_zhangxingcai:die": "战骨黄沙埋，空见归乡魂。",
    //赵襄
	"#firefengpo1": "先魂远守，填西川地陷。",
    "#firefengpo2": "英灵助力，扶炎汉天青。",
	"#firelonghun1": "继续，战斗！",
    "#firelonghun2": "为了你们，我会战斗到最后一刻。",
    "#firelonghun3": "我是龙魂的继承者！",
	"#firehunyou1": "请借给我，你们的力量！",
    "#firehunyou2": "先辈们，赐予我力量吧！",
    "#firejueqi1": "逝者如斯，亘古长流，唯英烈之魂悬北斗而长存！",
    "#firejueqi2": "赵氏之女，跪祈诸公勿渡黄泉，暂留人间，佑大汉万年！",
    "#firejueqi3": "龙凤在侧，五虎在前，天命在汉，既寿永昌！",
    "#firejueqi4": "人言为信，日月为明，言日月为证，佑大汉长明！",
    "#fireyigong1": "凝傲雪之梅为魄，英魂长存，独耀山河万古明！",
    "#fireyigong2": "铸凌霜之寒成剑，青锋出鞘，斩尽天下不臣贼！",
    "#fireyigong3": "当年明月凝霜刃，此日送尔渡黄泉！",
    "#fireyigong4": "已识万里乾坤大，何虑千山草木青！",
    "#fire_zhaoxiang:die": "大厦将倾，空余泪两行。",
    //姜维
	"#firelinyan1": "三尺台上释千古，一曲谱半生，影随光而行。",
    "#firelinyan2": "影绎当年蹉跎，戏如人生，几声锣鼓惊春风。",
    "#firelinyan3": "炎阳在悬，岂因乌云障日，而弃金光于野？",
    "#firelinyan4": "怀麒麟之志，负柱国之托，奔天涯海角！",
    "#firelinyan5": "天道昭昭，士如夸父，所逐者忠贞之志尔！",
    "#firelinyan6": "炎阳在悬，紫薇居北，士不可以不弘毅！",
    "#fireranji1": "秉笔客书江湖事，执灯叟照当年人。",
    "#fireranji2": "皮影话峥嵘，千古兴亡事，一杯浊酒中。",
    "#fireranji3": "孤鸿鸣于野，其以身为凤，引春风入汉关。",
    "#fireranji4": "古来圣贤卫道而死，道之存焉何惜深入九渊？",
    "#fireranji5": "舍身入鼎，薪火独耀，此躯可照曰月山河否？",
    "#fireranji6": "天下齐喑，我辈秉身为烛，当照四海九州！",
    "#fireyujun1": "浮生路长，若得遇知己，何其幸哉。",
    "#fireyujun2": "你我虽各为其主，然不乏相惜之谊。",
    "#fireyujun3": "九州齐喑，我辈燃己长明，君欲同否？",
    "#fireyujun4": "英才救世，从者皆众，请君拨乱反正。",
    "#fireyujun5": "君才胜司马氏十倍，何故居于人下？",
    "#fireyujun6": "国破家亡，君乃最后一线之生机。",
    "#fire_jiangwei:die": "今日同死，亦无所憾！",
};
const 欲雨临泽taici = {
    //陆抗
	"#waterkegou1": "各保分界，无求细利。",
    "#waterkegou2": "胸怀千万，彰其德，包其柔。",
    "#waterkegou3": "彼专为德，我专为暴，是不战而自服也。",
    "#waterkegou4": "一邑一乡，不可以无信义。",
    "#waterposhi1": "破羊枯之策，势在必行。",
    "#waterposhi2": "破晋军分进合击之势，牵晋军主力之实。",
    "#waterposhi3": "破晋军雄威，断敌心谋略。",
    "#waterposhi4": "良谋益策，破敌腹背。",
    "#water_lukang:die": "吾即亡矣，吴又能存几时?",
    //陆逊
	"#waterjunlve1": "诱敌而入，以待破敌之机。",
    "#waterjunlve2": "统军之法，不唯以死相拼。",
    "#watercuike1": "摧其壁垒，克其之营。",
    "#watercuike2": "如此扎寨，牵一发而动全身。",
    "#waterzhanhuo1": "绽火如绽旗，一网打尽！",
    "#waterzhanhuo2": "凭风借势，以火代兵！",
    "#water_luxun:die": "唉...我这算是覆鹿寻蕉之过吗.....",
    //孙策
	"#waterjiang1": "江东有吾足矣，余者俱听命称臣！",
    "#waterjiang2": "今不俯首系颈，明日便尸骨无存！",
    "#waterhunzi1": "力攻平江东，威名扬天下！",
    "#waterhunzi2": "翻江复倒海，六合定乾坤！",
    "#wateryinghun1": "吾掌中之物，尔等安敢染指！",
    "#wateryinghun2": "有违吾意者，此子便是下场！",
    "#water_sunce:die": "尔等宵小！穷极龌龊之能事……",
    //孙尚香
	"#waterbeiwu1": "风雨如晦，鸡鸣不已，既见君子，云胡不喜？",
    "#waterbeiwu2": "吾至爱君，唯愿执子之手，与子携老。",
    "#waterxiaoji1": "青丝妆白雪，箭射南来之雁，劫青乌之锦书。",
    "#waterxiaoji2": "仗剑行江海，女儿负鼎力，不羡虞姬随霸王。",
    "#waterliangzhu1": "采君之桃李，此物相思，不畏万水千山。",
    "#waterliangzhu2": "受君之琼瑶，无所为报，唯愿此生不离。",
    "#water_sunshangxiang:die": "江南流水归海心，我愿随水佑吴盛。",
    //孙寒华
	"#waterhuiling1": "静则潜修至道，动则行善累功。",
    "#waterhuiling2": "阳炁冲三关，斩尸除阴魔。",
    "#waterhuiling3": "慧剑断情除旧妄，一心向道为苍生。",
    "#waterhuiling4": "蒲团清静坐，神归了道真。",
    "#watertaji1": "谨以三尺神锋，代天行化，布令宣威。",
    "#watertaji2": "步天罡，踏北斗，有秽皆除，无妖不斩。",
    "#watertaji3": "剑斩魔头，观万灵慑服，群妖束手！",
    "#watertaji4": "一人一剑，往荡平魔窟，再塑人间！",
    "#waterqinghuang1": "执护道之宝器，御万邪之侵袭。",
    "#waterqinghuang2": "刀兵水火，速离身形。",
    "#waterqinghuang3": "定吾三魂七魄，保其不得丧清。",
    "#waterqinghuang4": "体有金光，覆映吾身。",
    "#water_sunhanhua:die": "身腾紫云天门去，随生复感又照明!",
};
const 惊鸿玉蝶taici = {
    //貂蝉
	"#icelijian1": "好哥哥，是妾身美，还是妾身奏的曲子美?",
    "#icelijian2": "妾身好累，除非将军满饮，不然我便不奏乐了哦。",
    "#icebiyue1": "佳人独舞，瑶光曼丽，今夕谁与共消愁?",
    "#icebiyue2": "月上枝头，星满金秋，柔指采蝶妆红袖。",
    "#ice_diaochan:die": "月下红颜，终随流水去。",
    //吕玲绮
	"#icewushuang1": "策马冲阵，铁骑过处尽皆胆寒!",
    "#icewushuang2": "挥戟断兵，何人敢挡虓虎之女?",
	"#iceshenwu1": "烽烟遍地，巾帼逞英。",
    "#iceshenwu2": "巾帼为将，不弱男儿。",
    "#iceshenwei1": "贵勇无惧，奋力先登!",
    "#iceshenwei2": "披坚执锐，傲气凌人!",
    "#ice_lvlingqi:die": "沙场为国死，马革裹尸还。",
    //张宁
	"#icetianze1": "独立而不改，周行而不殆。",
    "#icetianze2": "四时变化，日月更替，天之则也。",
	"#icedifa1": "地之法，土形气形，物因以生。",
    "#icedifa2": "气行乎地中，其行也因地之势。",
    "#ice_zhangning:die": "天地之变，畏之非也。",
    //张琪瑛
	"#icefalu1": "勾陈引麒麟戊日日仁，后土继天雷承运名御。",
    "#icefalu2": "紫微星銮冲九宫之虚，玉清元始化三清之祖。",
    "#icefalu3": "斗虚盈三清之气而冲牛，撷赤虹凌霄，点紫微之绛唇。",
    "#icefalu4": "星守贯太虚之宫而惊鸾，被兜率婧霞，引银河之流星。",
    "#icedianhua1": "虫石草木皆有其灵智，一朝点塞、飞升在即。",
    "#icedianhua2": "天上仙人称凡人为顽石，我自有点石成金之妙法。",
    "#icedianhua3": "曾乘青鸾过蓬菜，紫鲛捧玉，赤鲤吐珠，一梦登仙途。",
    "#icedianhua4": "狐鸣青丘，烛龙千里，共工折柱不周，其仙也，非兽焉。",
    "#icezhenyi1": "彼登西山，采薇而食，非五谷之不膏慕先贤之真璞。",
    "#icezhenyi2": "春米五斗，散于山泽，邀山鬼之飨宴，惊林间之睡狐。",
    "#icezhenyi3": "白鸥引醴泉之水，青鹿衔牡野之苹，冯虚御风，可称仙仪。",
    "#icezhenyi4": "朱雀献首阳之火，玄龟捧息洪之壤，涅槃造化，方成真我。",
    "#ice_zhangqiying:die": "韶华不为人间留，恨悠悠，几时休?",
    //曹婴
	"#icelingren1": "尔等于我，如着亵衣之黄口于持兵戈之锐士！",
    "#icelingren2": "夫为将者，其行雷厉，其兵骁果，其势凌人！",
    "#icelingren3": "秉凌人之盛气，试青锋于万里！",
    "#icelingren4": "斩宵小于沙场，绝仇雠于疆野！",
    "#icefujian1": "尔军中持戈之护卫，造饭之庖厨，饲马之御者皆为我军耳目！",
    "#icefujian2": "汝营兵将几何，粮草多少，箭矢盈亏，我已了然于胸。",
    "#icefujian3": "紫电耀魍魉之遁形，青霜斩魑魅之神魄。",
    "#icefujian4": "纵汝亡命天涯海角，吾亦逐之负首而还。",
    "#icelingren_guixin1": "太公曾教我一言，宁许我负人不许人负我。",
    "#icelingren_guixin2": "大仇在悬，没齿难忘，此日恩怨尽清。",
    "#icelingren_xingshang1": "尔等前往黄泉，此物留于人间，自可为我所用。",
    "#icelingren_xingshang2": "黄泉路远，袍泽慢行，待我报仇雪恨！",
    "#ice_caoying:die": "袍泽捐躯在野，此仇怎可归冢?",
};
const 爆料体验taici = {
    //神黄忠
	"#firelieqiong1": "横眉蔑风雨，引弓狩天狼！",
    "#firelieqiong2": "一箭出，万军毙！",
    "#firezhanjue1": "流不尽的英雄血，斩不尽的逆贼头！",
    "#firezhanjue2": "长刀渴血，当饲英雄胆！",
    "#fire_huangzhong:die": "箭雨曾蔽日，今夕却成绝响……",

    //武皇甫嵩
	"#icechaozhen1": "九州欲靖，未央待明，今甲光向日之时。",
    "#icechaozhen2": "身阻狂澜，手扶广厦，老臣此心如铁。",
	"#icelianjie1": "才战凉州罢，挥帜复河湟。",
    "#icelianjie2": "犯大汉天威者，虽远必诛!",
    "#icejiangxian1": "将军生白发，兀自横刀，立马啸西风。",
    "#icejiangxian2": "兴戈止战，愿天下再无烽火。",
    "#ice_huangfusong:die": "心不忘忠，何为不安?",

    //ol南华老仙
	"#iceqingshu1": "赤子青荒，唯记万变其一。",
    "#iceqingshu2": "天地万法，皆在此书之中。",
    "#iceqingshu3": "以小篆记大道，则道可道。",
	"#iceshoushu1": "此书载天地至理，望汝珍视如命。",
    "#iceshoushu2": "天书非凡物，字字皆玄机。",
    "#iceshoushu3": "我得道成仙，当出世化升人中。",
	"#icehedao1": "不参黄泉，难悟大道。",
    "#icehedao2": "道者，亦置之死地而后生。",
    "#icehedao3": "因果开茅塞，轮回似醍醐。",
    "#ice_nanhualaoxian:die": "尔生异心，必获恶报。",

    //武吕蒙
	"#waterjuxian1": "君子藏器于身，待时而动。",
    "#waterjuxian2": "枕戈待旦，怒极无为。",
    "#watershiji1": "攻心要害，以取胜券。",
	"#watershiji2": "知其底细，方能百战不殆。",
    "#watershiji3": "勤勉治学，文武兼顾。",
    "#watershiji4": "书卷万学，方知其意。",
	"#waterzhanxian1": "关羽实乃熊虎之将，必当预先谋断!",
    "#waterzhanxian2": "谋而取之，断而破之!",
    "#water_lvmeng:die": "望主公多思，吾不能再守了。",

};
const 异构Bosstaici = {
    //虎牢神吕布
	"#TAF_wushuang1": "此身此武天下无双。",
    "#TAF_wushuang2": "乘赤兔舞画戟斩将破敌，不过举手而为。",
	"#TAF_baguan1": "凭关镇敌，万夫莫开！",
    "#TAF_baguan2": "雄霸虎牢，一将当关。",
	"#TAF_zhanjia1": "战甲护体，金刚不坏！",
    "#TAF_zhanjia2": "明光宝甲，护我神躯。",
	"#TAF_xuli1": "力之所待，蓄势而发！",
    "#TAF_xuli2": "利刀缮甲，东山再起。",
	"#TAF_zhankai1": "兴战之铠，触之必伤！",
    "#TAF_zhankai2": "厌伤之胃，眶毗必报！",
	"#TAF_xiuluo1": "百战轮回锻神躯，我以修罗彰天魔！",
    "#TAF_xiuluo2": "六道何须论因果，独霸炼狱斩阎罗！",
	"#TAF_shenfeng1": "神锋出鞘，见血方还！",
    "#TAF_shenfeng2": "剑锋所指，万军辟易！",
	"#TAF_liechu1": "愤烈杵凿魂，叫尔等肝肠寸断！",
    "#TAF_liechu2": "断轮回六道，囚神佛，共淹黄泉！",
	"#TAF_fumo1": "锦袍失兮怅吾衣，才入魔兮再伏魔！",
    "#TAF_fumo2": "汝皇天威安敢犯？我化修罗伏天魔！",
	"#TAF_jingang1": "金刚怒问竖子，何堪修罗之怒？",
    "#TAF_jingang2": "佛陀悯劝来者，莫渡弱水黄泉？",
	"#TAF_shenji1": "断轮回，笑忘川，召旧部，战黄泉！",
    "#TAF_shenji2": "化修罗，修战予，斩三尸，征九天！",
	"#TAF_kuangbao_shadow1": "骨肉为宴，吾为战狂!",
    "#TAF_kuangbao_shadow2": "神魔现世，当负命而还!",
	"#TAF_xiuluo_shadow1": "百战轮回锻神躯，我以修罗彰天魔！",
    "#TAF_xiuluo_shadow2": "六道何须论因果，独霸炼狱斩阎罗！",
    "#TAF_lvbu_one:die": "战神不死，必将再起，其势更烈！！",
    "#TAF_lvbu_two:die": "战神不死，必将再起，其势更烈！！",
    "#TAF_lvbu_three:die": "战神不死，必将再起，其势更烈！！",

    //神鬼高达
	"#TAF_boss_juejing1": "置于死地，方能后生！",
    "#TAF_boss_juejing2": "背水一战，不胜便死！",
	"#TAF_boss_wushuang1": "萤烛之火，也敢与日月争辉？",
    "#TAF_boss_wushuang2": "鼠辈！螳臂当车！",
	"#TAF_boss_longhun1": "常山赵子龙在此！",
    "#TAF_boss_longhun2": "能屈能伸，才是大丈夫！",
	"#TAF_boss_jiwu1": "我，是不可战胜的！",
    "#TAF_boss_jiwu2": "今天，就让你们感受一下真正的绝望！",
	"#TAF_boss_shenqu1": "别心怀侥幸了，你们不可能赢！",
    "#TAF_boss_shenqu2": "虎牢关，我一人镇守足矣！",
	"#TAF_boss_xuanfeng1": "千钧之势，力贯苍穹！",
    "#TAF_boss_xuanfeng2": "横扫六合，威震八荒！",
	"#TAF_boss_wansha1": "蝼蚁，怎容偷生？",
    "#TAF_boss_wansha2": "沉沦吧，在这无边的恐惧！",
	"#TAF_boss_qiangxi1": "这么想死，那我就成全你！",
    "#TAF_boss_qiangxi2": "项上人头，待我来取！",
	"#TAF_boss_tieji1": "哈哈哈，破绽百出！",
    "#TAF_boss_tieji2": "我要让这虎牢关下，血流成河！",
    "#TAF_shenguigaoda:die": "你们的项上人头，我改日再取！龙身虽死，魂魄不灭！",
    "#TAF_shenguigaoda_shadow:die": "你们的项上人头，我改日再取！龙身虽死，魂魄不灭！",
};

const origintaici = {
    ...神话再临taici,
    ...隐忍天弓taici,
    ...鼎足三分taici,
    ...星河皓月taici,
    ...惊世银竹taici,
    ...期期离火taici,
    ...欲雨临泽taici,
    ...惊鸿玉蝶taici,
    ...爆料体验taici,
    ...异构Bosstaici,
};
function getVoice(obj) {
    let result = {};
    for (let key in obj) {
        const value = obj[key];
        //console.log([key,value]);
        let newkey = '';
        if (key.includes(':die')) {
            newkey = `#ext:银竹离火/audio/die/${key.replace('#', '')}`;
        } else {
            newkey = `#ext:银竹离火/audio/skill/${key.replace('#', '')}`;
        }
        result[newkey] = value;
    }
    return result;
}
/**
 * 角色台词
 */
export const voices = getVoice(origintaici);;